In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
dataset = pd.read_csv("new deaths dataset.csv", index_col='date', parse_dates=True)
print('shape',dataset.shape)
dataset.describe()

shape (500, 11)

,total_cases,new_cases,total_deaths,new_deaths,reproduction_rate,positive_rate,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,stringency_index
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,500.000000
mean,52728.956000,204.206000,383.742000,1.646000,1.122480,0.068814,2.869641e+04,24776.272000,3920.140000,241.36000,47.446220
std,32793.093696,296.233164,281.213438,3.354876,0.263627,0.061634,1.613339e+05,133943.541915,39060.971015,3144.28997,12.460919
min,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
25%,26460.250000,0.000000,142.750000,0.000000,0.997500,0.023000,0.000000e+00,0.000000,0.000000,0.00000,38.890000
50%,50544.000000,89.000000,323.000000,0.000000,1.170000,0.045000,0.000000e+00,0.000000,0.000000,0.00000,44.440000
75%,89893.000000,281.250000,734.000000,2.000000,1.252500,0.100000,0.000000e+00,0.000000,0.000000,0.00000,52.780000
max,102103.000000,1583.000000,823.000000,28.000000,1.550000,0.319000,1.271393e+06,865422.000000,405971.000000,48252.00000,86.110000

In [3]:
X = dataset[['positive_rate']]
Y = dataset[['new_deaths']]
scaler= MinMaxScaler()
X=scaler.fit_transform(X)
Y = scaler.fit_transform(Y)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.10, random_state=123, shuffle=False)

In [5]:
from sklearn.svm import SVR
linSVR = SVR(kernel='linear')
linSVR.fit(X_train, Y_train.ravel())

polySVR = SVR(kernel='poly', degree=2)
polySVR.fit(X_train, Y_train.ravel())

rbfSVR = SVR(kernel='rbf', C=1000.0, gamma=0.15)
rbfSVR.fit(X_train, Y_train.ravel())

SVR(C=1000.0, gamma=0.15)

In [6]:
Y_pred = rbfSVR.predict(X_test)

In [7]:
Y_pred.reshape(-1,1)

array([[0.10015475],
       [0.1002562 ],
       [0.10010748],
       [0.10013083],
       [0.10022996],
       [0.10017924],
       [0.10022996],
       [0.10022996],
       [0.10004078],
       [0.10006246],
       [0.10006246],
       [0.10006246],
       [0.10008469],
       [0.10008469],
       [0.09997901],
       [0.10001964],
       [0.10013083],
       [0.10010748],
       [0.10017924],
       [0.10020431],
       [0.10010748],
       [0.10013083],
       [0.10015475],
       [0.0999405 ],
       [0.09997901],
       [0.09997901],
       [0.09988667],
       [0.0998071 ],
       [0.09982202],
       [0.0999041 ],
       [0.0999041 ],
       [0.09976523],
       [0.09977871],
       [0.09977871],
       [0.099716  ],
       [0.09975223],
       [0.09970484],
       [0.09983744],
       [0.09979267],
       [0.09982202],
       [0.09976523],
       [0.09979267],
       [0.1005518 ],
       [0.1005518 ],
       [0.1005518 ],
       [0.1005518 ],
       [0.1005518 ],
       [0.1005518 ],
       [0.1005518 ],
       [0.1005518 ]])

In [8]:
y_testvy_pred =pd.concat([pd.DataFrame(Y_test), pd.DataFrame(Y_pred)], axis=1)

In [9]:
rev_trans= scaler.inverse_transform(y_testvy_pred)

In [10]:
final= pd.DataFrame(rev_trans)

In [11]:
final.columns=['new_deaths','predicted']
final

    new_deaths  predicted
0          0.0   2.804333
1          0.0   2.807173
2          2.0   2.803009
3          0.0   2.803663
4          0.0   2.806439
5          0.0   2.805019
6          0.0   2.806439
7          0.0   2.806439
8          1.0   2.801142
9          0.0   2.801749
10         0.0   2.801749
11         3.0   2.801749
12         0.0   2.802371
13         0.0   2.802371
14         1.0   2.799412
15         0.0   2.800550
16         0.0   2.803663
17         0.0   2.803009
18         0.0   2.805019
19         0.0   2.805721
20         1.0   2.803009
21         0.0   2.803663
22         0.0   2.804333
23         1.0   2.798334
24         0.0   2.799412
25         0.0   2.799412
26         0.0   2.796827
27         0.0   2.794599
28         0.0   2.795017
29         0.0   2.797315
30         1.0   2.797315
31         0.0   2.793427
32         0.0   2.793804
33         2.0   2.793804
34         2.0   2.792048
35         0.0   2.793062
36         1.0   2.791735
37         0.0   2.795448
38         4.0   2.794195
39         0.0   2.795017
40         4.0   2.793427
41         2.0   2.794195
42         0.0   2.815450
43         3.0   2.815450
44         0.0   2.815450
45         0.0   2.815450
46         4.0   2.815450
47         0.0   2.815450
48         2.0   2.815450
49         2.0   2.815450

In [12]:
from sklearn.metrics import mean_absolute_error
mae_new_deaths = mean_absolute_error(final['predicted'],final['new_deaths'])
print('Mean absolute error of new deaths is:',mae_new_deaths)

Mean absolute error of new deaths is: 2.2414695726857357